### ISSUE TITLE
Could script handles variable deprecation

### ISSUE THREAD

**Issue by gmella** [craigberry/audit_exist_5x_removals#3]
Not sure that is is the right place and relevant, but following a small issue on [eXide](https://github.com/eXist-db/eXide/pull/231), I wonder if script could be enhanced to detect use of some deprecated variables 

Thank your for such tool.

**Comment by craigberry** [comment]
I'm not aware of any way I can get a list of deprecated variables.  Are you?  In the case cited above, you would have been warned about util:catch, just not $err, so I think the suggestion to use try/catch instead of util:catch could be considered enough of a clue that one needs to read the documentation on try/catch.  But I'd be happy to add variable deprecations if I knew a way to get them.

**Comment by gmella** [comment]
I was not the people who made the rewriting and not aware of any other variable changes. I agree with your suggestion. 
Back to exception-message case it comes with the removal of [CatchFunction in the util module](https://github.com/eXist-db/exist/commit/10a06dfbe7451204ad61781353986b2fad525a42#diff-70164f4def3c78a93cd6697dc8ec5a45)

I let you close my issue and add  variable deprecations if multiples reasons come.

Your tool is really useful! Thx

**Comment by craigberry** [comment]
I was not involved in the rewrite either.  I think I will follow your suggestion and close this but we can always reopen if we find a way to get a list of deprecated variables.  I'm glad you find the script useful.
